// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgt8HLat4asluMdvS8n6Mjy40b8UJzGBU',
    appId: '1:981126213346:web:533f326e282df03588f8bb',
    messagingSenderId: '981126213346',
    projectId: 'helperapp-46849',
    authDomain: 'helperapp-46849.firebaseapp.com',
    storageBucket: 'helperapp-46849.firebasestorage.app',
    measurementId: 'G-LESGZ5F797',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA--eOmXGxQrJ52FBbcuwXHYwLOcA031gI',
    appId: '1:981126213346:android:ef1760152ea10e7488f8bb',
    messagingSenderId: '981126213346',
    projectId: 'helperapp-46849',
    storageBucket: 'helperapp-46849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXVRNSsHayKcVkm4szK9HTXJC6MgH6Afc',
    appId: '1:981126213346:ios:b8eb4ada5d228b7688f8bb',
    messagingSenderId: '981126213346',
    projectId: 'helperapp-46849',
    storageBucket: 'helperapp-46849.firebasestorage.app',
    iosBundleId: 'com.example.helper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXVRNSsHayKcVkm4szK9HTXJC6MgH6Afc',
    appId: '1:981126213346:ios:b8eb4ada5d228b7688f8bb',
    messagingSenderId: '981126213346',
    projectId: 'helperapp-46849',
    storageBucket: 'helperapp-46849.firebasestorage.app',
    iosBundleId: 'com.example.helper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgt8HLat4asluMdvS8n6Mjy40b8UJzGBU',
    appId: '1:981126213346:web:77236d44a54e06c988f8bb',
    messagingSenderId: '981126213346',
    projectId: 'helperapp-46849',
    authDomain: 'helperapp-46849.firebaseapp.com',
    storageBucket: 'helperapp-46849.firebasestorage.app',
    measurementId: 'G-J2QDCFQ3GZ',
  );

}